import { z } from "zod";

export const applicationErrorCodeSchema = z.enum([
  "DOCUMENT_FORMAT_UNSUPPORTED",
  "DOCUMENT_SOURCE_INVALID",
  "DOCUMENT_SOURCE_TOO_LARGE",
  "DOCUMENT_NOT_FOUND",
  "DOCUMENT_REVISION_NOT_FOUND",
  "DOCUMENT_PROJECTION_UNAVAILABLE",
  "DOCUMENT_REVISION_UPDATE_REQUIRED",
  "RESOURCE_NOT_FOUND",
  "RESOURCE_UNAVAILABLE",
  "RESOURCE_RANGE_INVALID",
  "SOURCE_MAPPING_NOT_FOUND",
  "READING_POSITION_INVALID",
  "SELECTION_INVALID",
  "MODEL_PROVIDER_NOT_CONFIGURED",
  "MODEL_PROVIDER_FAILED",
  "MODEL_OUTPUT_INVALID",
  "TRANSLATION_NOT_FOUND",
  "LEXICAL_SOURCE_UNAVAILABLE",
  "LEXICAL_ENTRY_NOT_FOUND",
  "LEARNING_ITEM_INVALID",
  "EXPRESSION_NOT_FOUND",
  "LEARNING_CONTEXT_NOT_FOUND",
  "ANNOTATION_NOT_FOUND",
  "ANNOTATION_SOURCE_INVALID",
  "RECALL_MATCH_INVALID",
  "RECALL_OCCURRENCE_NOT_FOUND",
  "IMPORT_OPERATION_NOT_FOUND",
  "OPERATION_INTERRUPTED",
  "OPERATION_CANCELLED",
  "OPERATION_NOT_FOUND",
  "TASK_DEFINITION_NOT_FOUND",
  "WORKSPACE_SESSION_NOT_FOUND",
  "WORKSPACE_REFERENCE_INVALID",
  "IMPORT_FAILED",
  "INTERNAL_ERROR",
]);

export const applicationErrorSchema = z.object({
  code: applicationErrorCodeSchema,
  message: z.string().min(1),
  retryable: z.boolean(),
  operationId: z.string().min(1).optional(),
  traceId: z.string().min(1),
});

export type ApplicationErrorCode = z.infer<typeof applicationErrorCodeSchema>;
export type ApplicationError = z.infer<typeof applicationErrorSchema>;
